In [1]:
from torchsummary import summary
from scatter_resnet import *
import os
os.environ["CUDA_VISIBLE_DEVICES"]= ''

In [2]:
model = scatternet_cnn()
summary(model,(3,224,224))

nfscat 217.0
nspace 28.0
----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
 ScatteringTorch2D-1       [-1, 3, 217, 28, 28]               0
            Conv2d-2          [-1, 256, 28, 28]       1,500,160
              ReLU-3          [-1, 256, 28, 28]               0
            Conv2d-4          [-1, 256, 28, 28]          65,792
              ReLU-5          [-1, 256, 28, 28]               0
            Conv2d-6          [-1, 256, 28, 28]         590,080
              ReLU-7          [-1, 256, 28, 28]               0
            Conv2d-8          [-1, 256, 28, 28]         590,080
              ReLU-9          [-1, 256, 28, 28]               0
           Conv2d-10          [-1, 256, 28, 28]          65,792
             ReLU-11          [-1, 256, 28, 28]               0
       BasicBlock-12          [-1, 256, 28, 28]               0
           Conv2d-13          [-1, 256, 28, 28]          65,792
             R

In [3]:
model = scatternet_cnn()
summary(model,(3,224,224))

nfscat 217.0
nspace 28.0
----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
 ScatteringTorch2D-1       [-1, 3, 217, 28, 28]               0
            Conv2d-2          [-1, 256, 28, 28]       1,500,160
              ReLU-3          [-1, 256, 28, 28]               0
            Conv2d-4          [-1, 256, 28, 28]          65,792
              ReLU-5          [-1, 256, 28, 28]               0
            Conv2d-6          [-1, 256, 28, 28]         590,080
              ReLU-7          [-1, 256, 28, 28]               0
            Conv2d-8          [-1, 256, 28, 28]         590,080
              ReLU-9          [-1, 256, 28, 28]               0
           Conv2d-10          [-1, 256, 28, 28]          65,792
             ReLU-11          [-1, 256, 28, 28]               0
       BasicBlock-12          [-1, 256, 28, 28]               0
           Conv2d-13          [-1, 256, 28, 28]          65,792
             R

In [4]:
image = torch.ones((16,3,224,224))

In [5]:
model(image)

tensor([[0.5221, 0.4931, 0.4434,  ..., 0.4297, 0.5337, 0.6194],
        [0.5221, 0.4931, 0.4434,  ..., 0.4297, 0.5337, 0.6194],
        [0.5221, 0.4931, 0.4434,  ..., 0.4297, 0.5337, 0.6194],
        ...,
        [0.5221, 0.4931, 0.4434,  ..., 0.4297, 0.5337, 0.6194],
        [0.5221, 0.4931, 0.4434,  ..., 0.4297, 0.5337, 0.6194],
        [0.5221, 0.4931, 0.4434,  ..., 0.4297, 0.5337, 0.6194]],
       grad_fn=<SigmoidBackward>)

In [6]:
model

scatternet_cnn(
  (scattering): Scattering2D()
  (conv1): Conv2d(651, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (relu): ReLU(inplace=True)
  (layer1): Sequential(
    (0): BasicBlock(
      (relu): ReLU(inplace=True)
      (conv0): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1))
      (conv1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv3): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1))
    )
    (1): BasicBlock(
      (relu): ReLU(inplace=True)
      (conv0): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1))
      (conv1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv3): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1))
    )
  )
  (layer2): Sequential(
    (0): BasicBlock(
      (relu): ReLU(inplace=True)
      (conv0): Conv

In [7]:
print('conv1: ',model.conv1.weight.grad)
for layer in (model.layer1):
    print('###########################################\n layer1:')
    layer.output_grad()
for layer in (model.layer2):
    print('###########################################\n layer2: ')
    layer.output_grad()
print("fc layer: ",model.fc.weight.grad)

conv1:  None
###########################################
 layer1:
conv0: None
conv1: None
conv2: None
conv3: None
###########################################
 layer1:
conv0: None
conv1: None
conv2: None
conv3: None
###########################################
 layer2: 
conv0: None
conv1: None
conv2: None
conv3: None
###########################################
 layer2: 
conv0: None
conv1: None
conv2: None
conv3: None
fc layer:  None


In [8]:
import torch

In [9]:
o = torch.rand(3,1000)

In [10]:
o.shape

torch.Size([3, 1000])

In [11]:
torch.topk(o, dim=1, k=5).indices

tensor([[553, 489, 195, 972, 267],
        [865, 242, 463, 465, 813],
        [959, 203,  98, 724, 354]])

In [12]:
tar = torch.tensor([267, 463, 959])

In [17]:
top5 = torch.topk(o, dim=1, k=5).indices

In [21]:
top5

tensor([[553, 489, 195, 972, 267],
        [865, 242, 463, 465, 813],
        [959, 203,  98, 724, 354]])

In [18]:
torch.sum((top5-tar[:, None]) == 0)

tensor(3)

In [26]:
torch.sum((top5[:, 0]-tar)== 0)

tensor(1)

In [28]:
8/20*60

24.0